### PR TITLE
Fix docs around run

### LINKED ISSUE #128: Reactor compiler errors when using run/3 function
**Describe the bug**
The documentation states that using a non-module `run` function inside a `step` should have arity 3. But when that's supplied one gets and error claiming it should be `run/2` or `run/1` instead. Either the verification is wrong or the docs are wrong.

**To Reproduce**
```ex
defmodule FooReactor do
  use Reactor

  input(:foo)

  step :do_foo do
    run fn _, _, _ ->
      {:ok, :noop}
    end
  end
end
```

Produces the error:

```
== Compilation error in file lib/foo.ex ==
** (Spark.Error.DslError) [FooReactor]
reactor -> step -> do_foo:
  expected :run option to match at least one given type, but didn't match any. Here are the reasons why it didn't match each of the allowed types:

  * expected MFA or function of arity 2 in :run option, got: &FooReactor.run_0_generated_8536D4A244549FB51F4D5E7554E6D6E2/3
  * expected MFA or function of arity 1 in :run option, got: &FooReactor.run_0_generated_8536D4A244549FB51F4D5E7554E6D6E2/3
    (reactor 0.10.0) /Users/e/Code/ekg/deps/spark/lib/spark/dsl/extension.ex:1174: Reactor.Dsl.Reactor.Step.__build__/3
    (spark 2.2.30) lib/spark/dsl/extension/entity.ex:91: Spark.Dsl.Extension.Entity.handle/6
    lib/foo.ex:27: (module)
```
```

**Expected behavior**
Either the verifier is updated to match the docs, or the docs are updated to match the verifier.

**Runtime**
 - Spark version: `2.2.30`
 - Version: `0.10.0`

**Additional context**
If this is just an issue with the docs, please let me know! I'm happy to open a PR to fix them

### PR DESCRIPTION
**Pull request by ekosz**
This PR fixes #128 and a small test that was warning. It mostly focuses on correcting the documentation around how the anonymous `run` function should be used within a step.

# Contributor checklist

- [X] Bug fixes include regression tests
- [X] Documentation changes

### CODE REVIEW

File: lib/reactor/dsl/step.ex [hunk 1]
```diff
@@ -90,29 +90,29 @@ defmodule Reactor.Dsl.Step do
...
-          Provide an anonymous function which implements the `undo/4` callback. Cannot be provided at the same time as the `impl` argument.
+          Provide an anonymous function which implements a `undo/1`, `undo/2`, or `undo/3` callback. Cannot be provided at the same time as the `impl` argument.
           """
         ],
         compensate: [
           type: {:or, [{:mfa_or_fun, 1}, {:mfa_or_fun, 2}, {:mfa_or_fun, 3}]},
           required: false,
           doc: """
-          Provide an anonymous function which implements the `undo/4` callback. Cannot be provided at the same time as the `impl` argument.
+          Provide an anonymous function which implements a `compensate/1`, `compensate/2`, or `compensate/3` callback. Cannot be provided at the same time as the `impl` argument.
```
Comment (zachdaniel) [inline lib/reactor/dsl/step.ex:107]:
```suggestion
          Provide an anonymous function which implements a `compensate/1-3` callback. Cannot be provided at the same time as the `impl` argument.
```

File: lib/reactor/dsl/step.ex [hunk 2]
```diff
@@ -90,29 +90,29 @@ defmodule Reactor.Dsl.Step do
...
-          Provide an anonymous function which implements the `run/3` callback. Cannot be provided at the same time as the `impl` argument.
+          Provide an anonymous function which implements a `run/1` or `run/2` callback. Cannot be provided at the same time as the `impl` argument.
           """
         ],
         undo: [
           type: {:or, [{:mfa_or_fun, 1}, {:mfa_or_fun, 2}, {:mfa_or_fun, 3}]},
           required: false,
           doc: """
-          Provide an anonymous function which implements the `undo/4` callback. Cannot be provided at the same time as the `impl` argument.
+          Provide an anonymous function which implements a `undo/1`, `undo/2`, or `undo/3` callback. Cannot be provided at the same time as the `impl` argument.
```
Comment (zachdaniel) [inline lib/reactor/dsl/step.ex:100]:
```suggestion
          Provide an anonymous function which implements a `undo/1-3` callback. Cannot be provided at the same time as the `impl` argument.
```

File: lib/reactor/dsl/step.ex [hunk 3]
```diff
@@ -90,29 +90,29 @@ defmodule Reactor.Dsl.Step do
           type: {:or, [{:mfa_or_fun, 1}, {:mfa_or_fun, 2}]},
           required: false,
           doc: """
-          Provide an anonymous function which implements the `run/3` callback. Cannot be provided at the same time as the `impl` argument.
+          Provide an anonymous function which implements a `run/1` or `run/2` callback. Cannot be provided at the same time as the `impl` argument.
```
Comment (zachdaniel) [inline lib/reactor/dsl/step.ex:93]:
```suggestion
          Provide an anonymous function which implements a `run/1-2` callback. Cannot be provided at the same time as the `impl` argument.
```

**Review by zachdaniel — APPROVED** [review]
Small readability suggestion, but only if you agree. Its pretty much the same thing regardless.

**Comment by ekosz** [comment]
Sounds good! Sorry still new to Elixir and it's documentation patterns. I'll update the PR

**Comment by ekosz** [comment]
All set

**Comment by zachdaniel** [comment]
I'm actually not sure my suggestion was conventional or not. Either way, its right now when it was wrong before, 🙇
